/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a408ede0-92e5-4073-bebd-813b2d98e3c9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_dyczuZfES",
    "aws_user_pools_web_client_id": "75j0oa90t024cu6r22vvjja0h3",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://azl4mgnctvcs7fmyzvvf4tmvha.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bk4csxpodnb3laqqhj4yk4a4mu",
    "aws_user_files_s3_bucket": "mealimages51214-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
